const users = [
  {
    id: 1,
    name: "Ռոման",
    teach: "React.js",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/19.png?v=1.1",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 2,
    name: "Անդրանիկ",
    teach: "Full-Stack",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/3.png?v=1.2",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 3,
    name: "Նարեկ",
    teach: "JavaScript",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/2.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 4,
    name: "Էմիլ",
    teach: "Front-End",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/5.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 5,
    name: "Ալբերտ",
    teach: "Python / ML",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/6.png?v=1.2",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 6,
    name: "Անուշավան",
    teach: "React.js",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/7.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 7,
    name: "Քրիստինե",
    teach: "JavaScript",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/11.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 8,
    name: "էրիկ",
    teach: "PHP / Laravel",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/8.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 9,
    name: "Ալբերտ",
    teach: "Python / ML",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/12.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 10,
    name: "Ֆրուժետա",
    teach: "HTML / CSS",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/13.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 11,
    name: "Վարդգես",
    teach: "Python / Django",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/14.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 12,
    name: "Հայկ",
    teach: "HTML / CSS",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/15.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 13,
    name: "Գոռ",
    teach: "Python / OOP",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/16.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 14,
    name: "Նարեկ",
    teach: "React.js",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/17.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 15,
    name: "Աղասի",
    teach: "Java",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/18.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 16,
    name: "Էդգար",
    teach: "MERN-Stack",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/1.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 17,
    name: "Արթուր",
    teach: "React.js",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/7.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 18,
    name: "Զմրուխտ",
    teach: "HTML / CSS",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/20.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 19,
    name: "Էրիկ",
    teach: "Java",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/22.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 20,
    name: "Արման",
    teach: "HTML / CSS",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/23.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 21,
    name: "Սերգեյ",
    teach: "Front-End",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/24.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 22,
    name: "Վահե",
    teach: "HTML / CSS",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/26.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
  {
    id: 23,
    name: "Արտյոմ",
    teach: "Front-End",
    Trainer: "Trainer",
    image: "https://smartcode.am/public/image/staff/25.png",
    gif: "https://s6.gifyu.com/images/S6GkA.gif",
  },
]

export default users
